<a href="https://colab.research.google.com/github/Gautamkhushboo/Pattern-Recognition-Lab-/blob/main/practical_no_1_PR(25).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

In [ ]:
customers = {
    "C1": [5000, 5, 4, 30],
    "C2": [5200, 6, 5, 35],
    "C3": [2000, 2, 3, 10]
}

data = np.array(list(customers.values()))
names = list(customers.keys())

print("Customer Data:\n", data)

Customer Data:
 [[5000    5    4   30]
 [5200    6    5   35]
 [2000    2    3   10]]


In [ ]:
euclidean = euclidean_distances(data)

print("Euclidean Distance:\n")
print(euclidean)

Euclidean Distance:

[[   0.          200.06748861 3000.06833256]
 [ 200.06748861    0.         3200.10077966]
 [3000.06833256 3200.10077966    0.        ]]


In [ ]:
from sklearn.metrics import pairwise_distances

manhattan = pairwise_distances(data, metric='manhattan')

print("Manhattan Distance:\n")
print(manhattan)

Manhattan Distance:

[[   0.  207. 3024.]
 [ 207.    0. 3231.]
 [3024. 3231.    0.]]


In [ ]:
cosine = cosine_similarity(data)

print("Cosine Similarity:\n")
print(cosine)

Cosine Similarity:

[[1.         0.99999971 0.99999926]
 [0.99999971 1.         0.99999835]
 [0.99999926 0.99999835 1.        ]]


In [ ]:
def most_similar(sim_matrix, names):
    n = len(names)
    for i in range(n):
        best_score = -1
        best_match = None

        for j in range(n):
            if i != j:
                if sim_matrix[i][j] > best_score:
                    best_score = sim_matrix[i][j]
                    best_match = names[j]

        print(f"{names[i]} → most similar to {best_match} (score: {best_score:.2f})")

In [ ]:
most_similar(cosine, names)

C1 → most similar to C2 (score: 1.00)
C2 → most similar to C1 (score: 1.00)
C3 → most similar to C1 (score: 1.00)


In [ ]:
!pip install python-Levenshtein

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 33.8 MB/s eta 0:00:00


In [ ]:
import Levenshtein

In [ ]:
sequences = {
    "C1": "ELECTRONICS BOOKS FASHION",
    "C2": "ELECTRONICS BOOKS FASHION",
    "C3": "GROCERY FOOD UTILITIES"
}

seq_names = list(sequences.keys())
seq_values = list(sequences.values())

for i in range(len(seq_values)):
    for j in range(len(seq_values)):
        if i != j:
            dist = Levenshtein.distance(seq_values[i], seq_values[j])
            print(f"{seq_names[i]} - {seq_names[j]} = {dist}")

C1 - C2 = 0
C1 - C3 = 20
C2 - C1 = 0
C2 - C3 = 20
C3 - C1 = 20
C3 - C2 = 20
